#!/usr/bin/env bash
# OPEN-271: generate and store the ddp_local_replication role's password in AWS Secrets Manager,
# matching this project's existing convention for RDS credentials (see
# deploy/rotate-database-url.sh, which reads the RDS master secret the same way). The password
# is generated by Secrets Manager itself and never appears in this script, this shell's history,
# or any file -- it exists only inside the secret this command creates.
#
# Run ONCE, by an identity with secretsmanager:CreateSecret (the same identity that will run
# 02-setup.sh against RDS). Safe to skip if this secret already exists -- check first with
# `aws secretsmanager describe-secret --secret-id ddp-openstates/ddp_local_replication` before
# re-running, since re-running create-secret on an existing secret ID fails loudly rather than
# silently overwriting (which is the correct, safe default -- don't route around that failure).
set -euo pipefail

SECRET_ID="ddp-openstates/ddp_local_replication"
REGION="us-east-1"

aws secretsmanager create-secret \
  --region "$REGION" \
  --name "$SECRET_ID" \
  --description "OPEN-271: password for the ddp_local_replication role (logical replication to the Mac Studio, PLAN-rds-local-postgres-replication.md). Read-only replication credential, never handed to a consumer -- see ops/postgres-replica/README for the full role model." \
  --generate-secret-string '{"PasswordLength": 32, "ExcludePunctuation": true, "ExcludeUppercase": false}'

echo "Secret created at $SECRET_ID -- run 02-setup.sh next, it reads this secret directly."
