#!/usr/bin/env bash
# OPEN-271: generate and store the ddp_local_replication role's password in AWS Secrets Manager,
# matching this project's existing convention for RDS credentials (see
# deploy/rotate-database-url.sh, which reads the RDS master secret the same way). The password is
# generated by Secrets Manager itself and never appears in this shell's history or as any
# command's argument (a bare `--secret-string "$PASSWORD"` would put it in this process's own argv,
# visible to anything that can list processes on this box while the command runs -- passed via a
# private, immediately-deleted temp file instead, see below).
#
# Run ONCE, by an identity with secretsmanager:CreateSecret (the same identity that will run
# 02-setup.sh against RDS). Safe to skip if this secret already exists -- check first with
# `aws secretsmanager describe-secret --secret-id ddp-openstates/ddp_local_replication` before
# re-running, since re-running create-secret on an existing secret ID fails loudly rather than
# silently overwriting (which is the correct, safe default -- don't route around that failure).
set -euo pipefail

SECRET_ID="ddp-openstates/ddp_local_replication"
REGION="us-east-1"

# Bug fix, found live during OPEN-273's real execution: `create-secret` has no
# `--generate-secret-string` flag at all (confirmed via `aws secretsmanager create-secret help`
# showing no such parameter, on the AWS CLI version installed for this project) -- the original
# version of this script would have failed outright. The correct two-step pattern is to generate
# the password server-side via `get-random-password`, then pass it to `create-secret`.
#
# Correction, found in this fix's own review: an earlier version of this fix passed the password
# as `--secret-string "$RANDOM_PASSWORD"` directly -- that puts the real password in this
# process's own argv, visible via `ps` (etc.) to anything that can list processes on this box
# while the command runs, which is exactly the exposure this script's header comment claims to
# avoid. Fixed by writing it to a private (mode 600), immediately-deleted temp file instead and
# passing `--secret-string file://...`, which AWS CLI reads directly without ever putting the
# content on the command line.
RANDOM_PASSWORD="$(aws secretsmanager get-random-password \
  --region "$REGION" \
  --password-length 32 \
  --exclude-punctuation \
  --query 'RandomPassword' --output text)"

password_file="$(mktemp)"
chmod 600 "$password_file"
trap 'rm -f "$password_file"' EXIT
printf '%s' "$RANDOM_PASSWORD" > "$password_file"

aws secretsmanager create-secret \
  --region "$REGION" \
  --name "$SECRET_ID" \
  --description "OPEN-271: password for the ddp_local_replication role (logical replication to the Mac Studio, PLAN-rds-local-postgres-replication.md). Read-only replication credential, never handed to a consumer -- see ops/postgres-replica/README for the full role model." \
  --secret-string "file://$password_file"

echo "Secret created at $SECRET_ID -- run 02-setup.sh next, it reads this secret directly."
